OUTPUT_PATH = "output"

STEAM_DOWNLOAD_SERVERS = [
    "cache1-tpe-hnet.steamcontent.com",
    "cache3-tpe-hnet.steamcontent.com",
    "cache4-tpe-hnet.steamcontent.com",
    "cache2-tpe-hnet.steamcontent.com",
    "cache12-tyo3.steamcontent.com",
    "cache10-tyo3.steamcontent.com",
    "cache8-tyo3.steamcontent.com",
    "cache7-tyo3.steamcontent.com",
    "google2.cdn.steampipe.steamcontent.com",
    "alibaba.cdn.steampipe.steamcontent.com",
    "cache11-tyo3.steamcontent.com",
    "cache9-tyo3.steamcontent.com",
    "cache2-tyo3.steamcontent.com",
    "cache3-tyo3.steamcontent.com",
    "cache1-tyo3.steamcontent.com",
    "cache10-hkg1.steamcontent.com",
    "cache9-hkg1.steamcontent.com",
    "cache4-hkg1.steamcontent.com",
    "cache2-hkg1.steamcontent.com",
    "cache6-hkg1.steamcontent.com",
    "cache8-hkg1.steamcontent.com",
    "cache7-hkg1.steamcontent.com",
    "cache11-hkg1.steamcontent.com",
    "cache12-hkg1.steamcontent.com",
    "cache5-hkg1.steamcontent.com",
    "cache3-hkg1.steamcontent.com",
    "cache4-tyo3.steamcontent.com"
]
